// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Timtek.SAR.Infrastructure.Persistence;

#nullable disable

namespace Timtek.SAR.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SarDbContext))]
    [Migration("20260419184828_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Timtek.SAR.Domain.Entities.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("DefaultAoRadiusKm")
                        .HasColumnType("REAL");

                    b.Property<int>("DefaultReputationScore")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ExtendedNotificationRadiusKm")
                        .HasColumnType("REAL");

                    b.Property<int>("KeeperInvitationExpiryDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeeperRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumReputationThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("Timtek.SAR.Domain.Entities.Organisation", b =>
                {
                    b.OwnsOne("Timtek.SAR.Domain.ValueObjects.ReputationPointValues", "ReputationPointValues", b1 =>
                        {
                            b1.Property<Guid>("OrganisationId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("ConfirmedSighting")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ReputationPts_ConfirmedSighting");

                            b1.Property<int>("DismissedSighting")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ReputationPts_DismissedSighting");

                            b1.Property<int>("EvidenceUpload")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ReputationPts_EvidenceUpload");

                            b1.Property<int>("EvidenceUploadCapPerCase")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ReputationPts_EvidenceUploadCapPerCase");

                            b1.Property<int>("FirstCaseBonus")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ReputationPts_FirstCaseBonus");

                            b1.Property<int>("FoundOutcome")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ReputationPts_FoundOutcome");

                            b1.Property<int>("JoinCase")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ReputationPts_JoinCase");

                            b1.Property<int>("MissedInScopeCase")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ReputationPts_MissedInScopeCase");

                            b1.Property<int>("RemovedFromCase")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ReputationPts_RemovedFromCase");

                            b1.Property<int>("SectorCompletion")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ReputationPts_SectorCompletion");

                            b1.Property<int>("TrackUpload")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ReputationPts_TrackUpload");

                            b1.HasKey("OrganisationId");

                            b1.ToTable("Organisations");

                            b1.WithOwner()
                                .HasForeignKey("OrganisationId");
                        });

                    b.Navigation("ReputationPointValues")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
